# -*- coding: utf-8 -*-
"""Kanpsack_Problem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P_js97yQPmjr6A-Cb_d5QmJUalt4pGq7
"""

def knapSack(W, wt, val,n):
    if (n==0 or W ==0):
        return 0
    if (wt[n-1]>W):
        return knapSack(W, wt, val, n-1)
    else:
        return max(val[n-1] + knapSack(W-wt[n-1], wt, val, n-1),
                   knapSack(W, wt, val, n-1))

val = []
wt = []
n = int(input("Enter the max size of the array:"))

print("Enter the profits of n items:")
for i in range (0,n):
    l = int(input())
    val.append(l)

print("Enter the weights of n items: ")
for i in range (0,n):
    m = int(input())
    wt.append(m)

W = int(input("Enter the weight of the KanpSack: "))

print(val)
print(wt)
print("The output of the user given Knapsack problem is: ", knapSack(W, wt, val, n))